--- drivers/misc/Makefile
+++ drivers/misc/Makefile
@@ -57,3 +57,4 @@
 obj-$(CONFIG_SAMSUNG_JACK)	+= sec_jack.o
 obj-$(CONFIG_USB_SWITCH_FSA9480)	+= fsa9480.o
 obj-$(CONFIG_SAMSUNG_MODEMCTL) += samsung_modemctl/
+obj-$(CONFIG_LIVE_OC)		+= live_oc.o
