--- drivers/misc/Makefile
+++ drivers/misc/Makefile
@@ -58,3 +58,4 @@
 obj-$(CONFIG_USB_SWITCH_FSA9480)	+= fsa9480.o
 obj-$(CONFIG_OMAP_DIE_TEMP_SENSOR)	+= omap_temp_sensor.o
 obj-$(CONFIG_LEDS_AN30259A)	+= leds-an30259a.o
+obj-$(CONFIG_TOUCH_WAKE)	+= touch_wake.o
